### ISSUE TITLE
Example Strategies not working with latest version?

### ISSUE THREAD

**Issue by xkaraman** [jesse-ai/example-strategies#7]
Hi,
I tried to use the example strategies found in this repo, but i can't get them to work.

I download candles as instructed by the tutorial for BTC-USDT symbol and then tried to backtest the strategies. All of them throw `InsufficientMargin: You cannot submit an order for $30371 when your margin balance is $19321` if in `futures` mode or `NegativeBalance: Balance cannot go below zero in spot market.` if in `spot` mode.

PyTest for jesse pass all of the tests with no issue.

Is there something i could do to fix this or am i doing something completely wrong?

**Comment by vietvudanh** [comment]
Same problem, the turtle strategy not even run because of API changed.
I am trying to understand the strategy & jesse code to make it works with new version of jesse. I will create a pull request if I succeed.

**Comment by cryptocoinserver** [comment]
Its actually not related to the strategies, but Jesses spot support. 
Try it with futures mode.
